CREATE PROCEDURE FindServers
@proc TEXT,
@RAM INT,
@SSD INT
AS
BEGIN

SELECT * FROM Servers 
WHERE Processor LIKE CONCAT('%', @proc, '%')
AND RAM =
	CASE WHEN @RAM < 0 THEN RAM
	ELSE @RAM END
AND SSD = 
	CASE WHEN @SSD < 0 THEN SSD
	ELSE @SSD END
AND ID NOT IN (SELECT ServerID FROM Orders)

END